# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 03:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_spiders', to=settings.AUTH_USER_MODEL),
        ),
    ]
